### ISSUE TITLE
검색 기능 API 설계

### ISSUE THREAD

**Issue by mingjji** [nhnacademy-be7-Ssacthree/etc#90]

**Comment by HyunKN** [comment]
태그 필터로 검색, 카테고리 필터로 검색 등 구현
검색 시 디테일한 부분 수정 가능하다면 수정하기

DBSync 도 조금 수정이 필요해 보임

**Comment by HyunKN** [comment]
페이지 구현, 카테고리 필터 구현 필요

**Comment by HyunKN** [comment]
카테고리 필터 완료, 페이지 구현 완료
